spring:
  application:
    name: notification-service-mirror
  kafka:
    consumer:
      group-id: notification-v2

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"